USE justraduz;

SET @sql := IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ai_results' AND COLUMN_NAME = 'modelo') = 0,
  'ALTER TABLE ai_results ADD COLUMN modelo VARCHAR(80) NULL AFTER confianca',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @sql := IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ai_results' AND COLUMN_NAME = 'prompt_versao') = 0,
  'ALTER TABLE ai_results ADD COLUMN prompt_versao VARCHAR(80) NULL AFTER modelo',
  'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
